/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: 04c2e8f4c4f48082f82cdbc4e1c02888)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ContainerClass";
	}
	interface Env {
		CF_TUNNEL: string;
		CONTAINER_DO: DurableObjectNamespace<import("./src/index").ContainerClass>;
	}
}
interface Env extends Cloudflare.Env {}
